### ISSUE TITLE
Auto release to PyPI which triggered by git tag with semver format

### ISSUE THREAD

**Issue by fkztw** [M157q/hor2vec#9]

**Comment by fkztw** [comment]
```
flit publish
Fetching list of valid trove classifiers               I-flit.validate
Traceback (most recent call last):
  File "/home/circleci/repo/venv/bin/flit", line 8, in <module>
    sys.exit(main())
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/flit/__init__.py", line 179, in main
    main(args.ini_file, repository, formats=set(args.format or []),
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/flit/upload.py", line 257, in main
    built = build.main(ini_path, formats=formats, gen_setup_py=gen_setup_py)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/flit/build.py", line 46, in main
    sdist_file = sb.build(dist_dir, gen_setup_py=gen_setup_py)
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/flit/sdist.py", line 223, in build
    return Path(super().build(str(target_dir), gen_setup_py=gen_setup_py))
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/flit_core/sdist.py", line 181, in build
    files_to_add = self.apply_includes_excludes(self.select_files())
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/flit/sdist.py", line 154, in select_files
    raise VCSError(
flit_core.common.VCSError: Untracked or deleted files in the source directory. Commit, undo or ignore these files in your VCS. ()

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by fkztw** [comment]
`flit publish` doesn't allow changes not staged for commit in VCS.
I just add `venv/` into `.gitignore`
https://github.com/M157q/hor2vec/commit/921f7e9b0041bece84fa4bd855b5ff8816921793

**Comment by M157q** [comment]
`flit publish` doesn't allow changes not staged for commit in VCS.
I just add `venv/` into `.gitignore`
https://github.com/M157q/hor2vec/commit/921f7e9b0041bece84fa4bd855b5ff8816921793
